package com.py.model;

import java.util.Date;

public class TaskInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.task_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String taskId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.pro_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String proId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.task_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String taskName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.parent_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.task_type
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String taskType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.urgency_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String urgencyFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.beg_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date begTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.end_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date endTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.beg_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date begTimeS;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.end_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date endTimeS;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.call_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date callTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.detail
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String detail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.status_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String statusFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.oper_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String operId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.oper_date
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private Date operDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.manger_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String mangerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.oper_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String operName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.remark
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column biz_safe_task_info.del_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	private String delFlag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.task_id
	 * @return  the value of biz_safe_task_info.task_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getTaskId() {
		return taskId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.task_id
	 * @param taskId  the value for biz_safe_task_info.task_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setTaskId(String taskId) {
		this.taskId = taskId == null ? null : taskId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.pro_id
	 * @return  the value of biz_safe_task_info.pro_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getProId() {
		return proId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.pro_id
	 * @param proId  the value for biz_safe_task_info.pro_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setProId(String proId) {
		this.proId = proId == null ? null : proId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.task_name
	 * @return  the value of biz_safe_task_info.task_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getTaskName() {
		return taskName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.task_name
	 * @param taskName  the value for biz_safe_task_info.task_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setTaskName(String taskName) {
		this.taskName = taskName == null ? null : taskName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.parent_id
	 * @return  the value of biz_safe_task_info.parent_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.parent_id
	 * @param parentId  the value for biz_safe_task_info.parent_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setParentId(String parentId) {
		this.parentId = parentId == null ? null : parentId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.task_type
	 * @return  the value of biz_safe_task_info.task_type
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getTaskType() {
		return taskType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.task_type
	 * @param taskType  the value for biz_safe_task_info.task_type
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setTaskType(String taskType) {
		this.taskType = taskType == null ? null : taskType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.urgency_flag
	 * @return  the value of biz_safe_task_info.urgency_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getUrgencyFlag() {
		return urgencyFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.urgency_flag
	 * @param urgencyFlag  the value for biz_safe_task_info.urgency_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setUrgencyFlag(String urgencyFlag) {
		this.urgencyFlag = urgencyFlag == null ? null : urgencyFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.beg_time
	 * @return  the value of biz_safe_task_info.beg_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getBegTime() {
		return begTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.beg_time
	 * @param begTime  the value for biz_safe_task_info.beg_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setBegTime(Date begTime) {
		this.begTime = begTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.end_time
	 * @return  the value of biz_safe_task_info.end_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.end_time
	 * @param endTime  the value for biz_safe_task_info.end_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.beg_time_s
	 * @return  the value of biz_safe_task_info.beg_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getBegTimeS() {
		return begTimeS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.beg_time_s
	 * @param begTimeS  the value for biz_safe_task_info.beg_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setBegTimeS(Date begTimeS) {
		this.begTimeS = begTimeS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.end_time_s
	 * @return  the value of biz_safe_task_info.end_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getEndTimeS() {
		return endTimeS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.end_time_s
	 * @param endTimeS  the value for biz_safe_task_info.end_time_s
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setEndTimeS(Date endTimeS) {
		this.endTimeS = endTimeS;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.call_time
	 * @return  the value of biz_safe_task_info.call_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getCallTime() {
		return callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.call_time
	 * @param callTime  the value for biz_safe_task_info.call_time
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setCallTime(Date callTime) {
		this.callTime = callTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.detail
	 * @return  the value of biz_safe_task_info.detail
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getDetail() {
		return detail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.detail
	 * @param detail  the value for biz_safe_task_info.detail
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setDetail(String detail) {
		this.detail = detail == null ? null : detail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.status_flag
	 * @return  the value of biz_safe_task_info.status_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getStatusFlag() {
		return statusFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.status_flag
	 * @param statusFlag  the value for biz_safe_task_info.status_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setStatusFlag(String statusFlag) {
		this.statusFlag = statusFlag == null ? null : statusFlag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.oper_id
	 * @return  the value of biz_safe_task_info.oper_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getOperId() {
		return operId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.oper_id
	 * @param operId  the value for biz_safe_task_info.oper_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setOperId(String operId) {
		this.operId = operId == null ? null : operId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.oper_date
	 * @return  the value of biz_safe_task_info.oper_date
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Date getOperDate() {
		return operDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.oper_date
	 * @param operDate  the value for biz_safe_task_info.oper_date
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setOperDate(Date operDate) {
		this.operDate = operDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.manger_id
	 * @return  the value of biz_safe_task_info.manger_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getMangerId() {
		return mangerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.manger_id
	 * @param mangerId  the value for biz_safe_task_info.manger_id
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setMangerId(String mangerId) {
		this.mangerId = mangerId == null ? null : mangerId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.oper_name
	 * @return  the value of biz_safe_task_info.oper_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getOperName() {
		return operName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.oper_name
	 * @param operName  the value for biz_safe_task_info.oper_name
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setOperName(String operName) {
		this.operName = operName == null ? null : operName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.remark
	 * @return  the value of biz_safe_task_info.remark
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.remark
	 * @param remark  the value for biz_safe_task_info.remark
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column biz_safe_task_info.del_flag
	 * @return  the value of biz_safe_task_info.del_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getDelFlag() {
		return delFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column biz_safe_task_info.del_flag
	 * @param delFlag  the value for biz_safe_task_info.del_flag
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag == null ? null : delFlag.trim();
	}
}