package com.py.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TaskInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public TaskInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andTaskIdIsNull() {
			addCriterion("task_id is null");
			return (Criteria) this;
		}

		public Criteria andTaskIdIsNotNull() {
			addCriterion("task_id is not null");
			return (Criteria) this;
		}

		public Criteria andTaskIdEqualTo(String value) {
			addCriterion("task_id =", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotEqualTo(String value) {
			addCriterion("task_id <>", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThan(String value) {
			addCriterion("task_id >", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
			addCriterion("task_id >=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThan(String value) {
			addCriterion("task_id <", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLessThanOrEqualTo(String value) {
			addCriterion("task_id <=", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdLike(String value) {
			addCriterion("task_id like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotLike(String value) {
			addCriterion("task_id not like", value, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdIn(List<String> values) {
			addCriterion("task_id in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotIn(List<String> values) {
			addCriterion("task_id not in", values, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdBetween(String value1, String value2) {
			addCriterion("task_id between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andTaskIdNotBetween(String value1, String value2) {
			addCriterion("task_id not between", value1, value2, "taskId");
			return (Criteria) this;
		}

		public Criteria andProIdIsNull() {
			addCriterion("pro_id is null");
			return (Criteria) this;
		}

		public Criteria andProIdIsNotNull() {
			addCriterion("pro_id is not null");
			return (Criteria) this;
		}

		public Criteria andProIdEqualTo(String value) {
			addCriterion("pro_id =", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdNotEqualTo(String value) {
			addCriterion("pro_id <>", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdGreaterThan(String value) {
			addCriterion("pro_id >", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdGreaterThanOrEqualTo(String value) {
			addCriterion("pro_id >=", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdLessThan(String value) {
			addCriterion("pro_id <", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdLessThanOrEqualTo(String value) {
			addCriterion("pro_id <=", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdLike(String value) {
			addCriterion("pro_id like", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdNotLike(String value) {
			addCriterion("pro_id not like", value, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdIn(List<String> values) {
			addCriterion("pro_id in", values, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdNotIn(List<String> values) {
			addCriterion("pro_id not in", values, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdBetween(String value1, String value2) {
			addCriterion("pro_id between", value1, value2, "proId");
			return (Criteria) this;
		}

		public Criteria andProIdNotBetween(String value1, String value2) {
			addCriterion("pro_id not between", value1, value2, "proId");
			return (Criteria) this;
		}

		public Criteria andTaskNameIsNull() {
			addCriterion("task_name is null");
			return (Criteria) this;
		}

		public Criteria andTaskNameIsNotNull() {
			addCriterion("task_name is not null");
			return (Criteria) this;
		}

		public Criteria andTaskNameEqualTo(String value) {
			addCriterion("task_name =", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameNotEqualTo(String value) {
			addCriterion("task_name <>", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameGreaterThan(String value) {
			addCriterion("task_name >", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameGreaterThanOrEqualTo(String value) {
			addCriterion("task_name >=", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameLessThan(String value) {
			addCriterion("task_name <", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameLessThanOrEqualTo(String value) {
			addCriterion("task_name <=", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameLike(String value) {
			addCriterion("task_name like", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameNotLike(String value) {
			addCriterion("task_name not like", value, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameIn(List<String> values) {
			addCriterion("task_name in", values, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameNotIn(List<String> values) {
			addCriterion("task_name not in", values, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameBetween(String value1, String value2) {
			addCriterion("task_name between", value1, value2, "taskName");
			return (Criteria) this;
		}

		public Criteria andTaskNameNotBetween(String value1, String value2) {
			addCriterion("task_name not between", value1, value2, "taskName");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNull() {
			addCriterion("parent_id is null");
			return (Criteria) this;
		}

		public Criteria andParentIdIsNotNull() {
			addCriterion("parent_id is not null");
			return (Criteria) this;
		}

		public Criteria andParentIdEqualTo(String value) {
			addCriterion("parent_id =", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotEqualTo(String value) {
			addCriterion("parent_id <>", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThan(String value) {
			addCriterion("parent_id >", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdGreaterThanOrEqualTo(String value) {
			addCriterion("parent_id >=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThan(String value) {
			addCriterion("parent_id <", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLessThanOrEqualTo(String value) {
			addCriterion("parent_id <=", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdLike(String value) {
			addCriterion("parent_id like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotLike(String value) {
			addCriterion("parent_id not like", value, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdIn(List<String> values) {
			addCriterion("parent_id in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotIn(List<String> values) {
			addCriterion("parent_id not in", values, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdBetween(String value1, String value2) {
			addCriterion("parent_id between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andParentIdNotBetween(String value1, String value2) {
			addCriterion("parent_id not between", value1, value2, "parentId");
			return (Criteria) this;
		}

		public Criteria andTaskTypeIsNull() {
			addCriterion("task_type is null");
			return (Criteria) this;
		}

		public Criteria andTaskTypeIsNotNull() {
			addCriterion("task_type is not null");
			return (Criteria) this;
		}

		public Criteria andTaskTypeEqualTo(String value) {
			addCriterion("task_type =", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeNotEqualTo(String value) {
			addCriterion("task_type <>", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeGreaterThan(String value) {
			addCriterion("task_type >", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeGreaterThanOrEqualTo(String value) {
			addCriterion("task_type >=", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeLessThan(String value) {
			addCriterion("task_type <", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeLessThanOrEqualTo(String value) {
			addCriterion("task_type <=", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeLike(String value) {
			addCriterion("task_type like", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeNotLike(String value) {
			addCriterion("task_type not like", value, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeIn(List<String> values) {
			addCriterion("task_type in", values, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeNotIn(List<String> values) {
			addCriterion("task_type not in", values, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeBetween(String value1, String value2) {
			addCriterion("task_type between", value1, value2, "taskType");
			return (Criteria) this;
		}

		public Criteria andTaskTypeNotBetween(String value1, String value2) {
			addCriterion("task_type not between", value1, value2, "taskType");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagIsNull() {
			addCriterion("urgency_flag is null");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagIsNotNull() {
			addCriterion("urgency_flag is not null");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagEqualTo(String value) {
			addCriterion("urgency_flag =", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagNotEqualTo(String value) {
			addCriterion("urgency_flag <>", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagGreaterThan(String value) {
			addCriterion("urgency_flag >", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagGreaterThanOrEqualTo(String value) {
			addCriterion("urgency_flag >=", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagLessThan(String value) {
			addCriterion("urgency_flag <", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagLessThanOrEqualTo(String value) {
			addCriterion("urgency_flag <=", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagLike(String value) {
			addCriterion("urgency_flag like", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagNotLike(String value) {
			addCriterion("urgency_flag not like", value, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagIn(List<String> values) {
			addCriterion("urgency_flag in", values, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagNotIn(List<String> values) {
			addCriterion("urgency_flag not in", values, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagBetween(String value1, String value2) {
			addCriterion("urgency_flag between", value1, value2, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andUrgencyFlagNotBetween(String value1, String value2) {
			addCriterion("urgency_flag not between", value1, value2, "urgencyFlag");
			return (Criteria) this;
		}

		public Criteria andBegTimeIsNull() {
			addCriterion("beg_time is null");
			return (Criteria) this;
		}

		public Criteria andBegTimeIsNotNull() {
			addCriterion("beg_time is not null");
			return (Criteria) this;
		}

		public Criteria andBegTimeEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time =", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time <>", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("beg_time >", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time >=", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeLessThan(Date value) {
			addCriterionForJDBCDate("beg_time <", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time <=", value, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeIn(List<Date> values) {
			addCriterionForJDBCDate("beg_time in", values, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("beg_time not in", values, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("beg_time between", value1, value2, "begTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("beg_time not between", value1, value2, "begTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNull() {
			addCriterion("end_time is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeIsNotNull() {
			addCriterion("end_time is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeEqualTo(Date value) {
			addCriterionForJDBCDate("end_time =", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <>", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("end_time >", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time >=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThan(Date value) {
			addCriterionForJDBCDate("end_time <", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time <=", value, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeIn(List<Date> values) {
			addCriterionForJDBCDate("end_time in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_time not in", values, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andEndTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time not between", value1, value2, "endTime");
			return (Criteria) this;
		}

		public Criteria andBegTimeSIsNull() {
			addCriterion("beg_time_s is null");
			return (Criteria) this;
		}

		public Criteria andBegTimeSIsNotNull() {
			addCriterion("beg_time_s is not null");
			return (Criteria) this;
		}

		public Criteria andBegTimeSEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time_s =", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSNotEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time_s <>", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSGreaterThan(Date value) {
			addCriterionForJDBCDate("beg_time_s >", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time_s >=", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSLessThan(Date value) {
			addCriterionForJDBCDate("beg_time_s <", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("beg_time_s <=", value, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSIn(List<Date> values) {
			addCriterionForJDBCDate("beg_time_s in", values, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSNotIn(List<Date> values) {
			addCriterionForJDBCDate("beg_time_s not in", values, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("beg_time_s between", value1, value2, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andBegTimeSNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("beg_time_s not between", value1, value2, "begTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSIsNull() {
			addCriterion("end_time_s is null");
			return (Criteria) this;
		}

		public Criteria andEndTimeSIsNotNull() {
			addCriterion("end_time_s is not null");
			return (Criteria) this;
		}

		public Criteria andEndTimeSEqualTo(Date value) {
			addCriterionForJDBCDate("end_time_s =", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSNotEqualTo(Date value) {
			addCriterionForJDBCDate("end_time_s <>", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSGreaterThan(Date value) {
			addCriterionForJDBCDate("end_time_s >", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time_s >=", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSLessThan(Date value) {
			addCriterionForJDBCDate("end_time_s <", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("end_time_s <=", value, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSIn(List<Date> values) {
			addCriterionForJDBCDate("end_time_s in", values, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSNotIn(List<Date> values) {
			addCriterionForJDBCDate("end_time_s not in", values, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time_s between", value1, value2, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andEndTimeSNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("end_time_s not between", value1, value2, "endTimeS");
			return (Criteria) this;
		}

		public Criteria andCallTimeIsNull() {
			addCriterion("call_time is null");
			return (Criteria) this;
		}

		public Criteria andCallTimeIsNotNull() {
			addCriterion("call_time is not null");
			return (Criteria) this;
		}

		public Criteria andCallTimeEqualTo(Date value) {
			addCriterionForJDBCDate("call_time =", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeNotEqualTo(Date value) {
			addCriterionForJDBCDate("call_time <>", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeGreaterThan(Date value) {
			addCriterionForJDBCDate("call_time >", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("call_time >=", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeLessThan(Date value) {
			addCriterionForJDBCDate("call_time <", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("call_time <=", value, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeIn(List<Date> values) {
			addCriterionForJDBCDate("call_time in", values, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeNotIn(List<Date> values) {
			addCriterionForJDBCDate("call_time not in", values, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("call_time between", value1, value2, "callTime");
			return (Criteria) this;
		}

		public Criteria andCallTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("call_time not between", value1, value2, "callTime");
			return (Criteria) this;
		}

		public Criteria andDetailIsNull() {
			addCriterion("detail is null");
			return (Criteria) this;
		}

		public Criteria andDetailIsNotNull() {
			addCriterion("detail is not null");
			return (Criteria) this;
		}

		public Criteria andDetailEqualTo(String value) {
			addCriterion("detail =", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotEqualTo(String value) {
			addCriterion("detail <>", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailGreaterThan(String value) {
			addCriterion("detail >", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailGreaterThanOrEqualTo(String value) {
			addCriterion("detail >=", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLessThan(String value) {
			addCriterion("detail <", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLessThanOrEqualTo(String value) {
			addCriterion("detail <=", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailLike(String value) {
			addCriterion("detail like", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotLike(String value) {
			addCriterion("detail not like", value, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailIn(List<String> values) {
			addCriterion("detail in", values, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotIn(List<String> values) {
			addCriterion("detail not in", values, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailBetween(String value1, String value2) {
			addCriterion("detail between", value1, value2, "detail");
			return (Criteria) this;
		}

		public Criteria andDetailNotBetween(String value1, String value2) {
			addCriterion("detail not between", value1, value2, "detail");
			return (Criteria) this;
		}

		public Criteria andStatusFlagIsNull() {
			addCriterion("status_flag is null");
			return (Criteria) this;
		}

		public Criteria andStatusFlagIsNotNull() {
			addCriterion("status_flag is not null");
			return (Criteria) this;
		}

		public Criteria andStatusFlagEqualTo(String value) {
			addCriterion("status_flag =", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagNotEqualTo(String value) {
			addCriterion("status_flag <>", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagGreaterThan(String value) {
			addCriterion("status_flag >", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagGreaterThanOrEqualTo(String value) {
			addCriterion("status_flag >=", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagLessThan(String value) {
			addCriterion("status_flag <", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagLessThanOrEqualTo(String value) {
			addCriterion("status_flag <=", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagLike(String value) {
			addCriterion("status_flag like", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagNotLike(String value) {
			addCriterion("status_flag not like", value, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagIn(List<String> values) {
			addCriterion("status_flag in", values, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagNotIn(List<String> values) {
			addCriterion("status_flag not in", values, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagBetween(String value1, String value2) {
			addCriterion("status_flag between", value1, value2, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andStatusFlagNotBetween(String value1, String value2) {
			addCriterion("status_flag not between", value1, value2, "statusFlag");
			return (Criteria) this;
		}

		public Criteria andOperIdIsNull() {
			addCriterion("oper_id is null");
			return (Criteria) this;
		}

		public Criteria andOperIdIsNotNull() {
			addCriterion("oper_id is not null");
			return (Criteria) this;
		}

		public Criteria andOperIdEqualTo(String value) {
			addCriterion("oper_id =", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdNotEqualTo(String value) {
			addCriterion("oper_id <>", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdGreaterThan(String value) {
			addCriterion("oper_id >", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdGreaterThanOrEqualTo(String value) {
			addCriterion("oper_id >=", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdLessThan(String value) {
			addCriterion("oper_id <", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdLessThanOrEqualTo(String value) {
			addCriterion("oper_id <=", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdLike(String value) {
			addCriterion("oper_id like", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdNotLike(String value) {
			addCriterion("oper_id not like", value, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdIn(List<String> values) {
			addCriterion("oper_id in", values, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdNotIn(List<String> values) {
			addCriterion("oper_id not in", values, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdBetween(String value1, String value2) {
			addCriterion("oper_id between", value1, value2, "operId");
			return (Criteria) this;
		}

		public Criteria andOperIdNotBetween(String value1, String value2) {
			addCriterion("oper_id not between", value1, value2, "operId");
			return (Criteria) this;
		}

		public Criteria andOperDateIsNull() {
			addCriterion("oper_date is null");
			return (Criteria) this;
		}

		public Criteria andOperDateIsNotNull() {
			addCriterion("oper_date is not null");
			return (Criteria) this;
		}

		public Criteria andOperDateEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date =", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <>", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateGreaterThan(Date value) {
			addCriterionForJDBCDate("oper_date >", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date >=", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateLessThan(Date value) {
			addCriterionForJDBCDate("oper_date <", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("oper_date <=", value, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date in", values, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("oper_date not in", values, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date between", value1, value2, "operDate");
			return (Criteria) this;
		}

		public Criteria andOperDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("oper_date not between", value1, value2, "operDate");
			return (Criteria) this;
		}

		public Criteria andMangerIdIsNull() {
			addCriterion("manger_id is null");
			return (Criteria) this;
		}

		public Criteria andMangerIdIsNotNull() {
			addCriterion("manger_id is not null");
			return (Criteria) this;
		}

		public Criteria andMangerIdEqualTo(String value) {
			addCriterion("manger_id =", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdNotEqualTo(String value) {
			addCriterion("manger_id <>", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdGreaterThan(String value) {
			addCriterion("manger_id >", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdGreaterThanOrEqualTo(String value) {
			addCriterion("manger_id >=", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdLessThan(String value) {
			addCriterion("manger_id <", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdLessThanOrEqualTo(String value) {
			addCriterion("manger_id <=", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdLike(String value) {
			addCriterion("manger_id like", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdNotLike(String value) {
			addCriterion("manger_id not like", value, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdIn(List<String> values) {
			addCriterion("manger_id in", values, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdNotIn(List<String> values) {
			addCriterion("manger_id not in", values, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdBetween(String value1, String value2) {
			addCriterion("manger_id between", value1, value2, "mangerId");
			return (Criteria) this;
		}

		public Criteria andMangerIdNotBetween(String value1, String value2) {
			addCriterion("manger_id not between", value1, value2, "mangerId");
			return (Criteria) this;
		}

		public Criteria andOperNameIsNull() {
			addCriterion("oper_name is null");
			return (Criteria) this;
		}

		public Criteria andOperNameIsNotNull() {
			addCriterion("oper_name is not null");
			return (Criteria) this;
		}

		public Criteria andOperNameEqualTo(String value) {
			addCriterion("oper_name =", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameNotEqualTo(String value) {
			addCriterion("oper_name <>", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameGreaterThan(String value) {
			addCriterion("oper_name >", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameGreaterThanOrEqualTo(String value) {
			addCriterion("oper_name >=", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameLessThan(String value) {
			addCriterion("oper_name <", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameLessThanOrEqualTo(String value) {
			addCriterion("oper_name <=", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameLike(String value) {
			addCriterion("oper_name like", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameNotLike(String value) {
			addCriterion("oper_name not like", value, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameIn(List<String> values) {
			addCriterion("oper_name in", values, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameNotIn(List<String> values) {
			addCriterion("oper_name not in", values, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameBetween(String value1, String value2) {
			addCriterion("oper_name between", value1, value2, "operName");
			return (Criteria) this;
		}

		public Criteria andOperNameNotBetween(String value1, String value2) {
			addCriterion("oper_name not between", value1, value2, "operName");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNull() {
			addCriterion("del_flag is null");
			return (Criteria) this;
		}

		public Criteria andDelFlagIsNotNull() {
			addCriterion("del_flag is not null");
			return (Criteria) this;
		}

		public Criteria andDelFlagEqualTo(String value) {
			addCriterion("del_flag =", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotEqualTo(String value) {
			addCriterion("del_flag <>", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThan(String value) {
			addCriterion("del_flag >", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
			addCriterion("del_flag >=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThan(String value) {
			addCriterion("del_flag <", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLessThanOrEqualTo(String value) {
			addCriterion("del_flag <=", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagLike(String value) {
			addCriterion("del_flag like", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotLike(String value) {
			addCriterion("del_flag not like", value, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagIn(List<String> values) {
			addCriterion("del_flag in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotIn(List<String> values) {
			addCriterion("del_flag not in", values, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagBetween(String value1, String value2) {
			addCriterion("del_flag between", value1, value2, "delFlag");
			return (Criteria) this;
		}

		public Criteria andDelFlagNotBetween(String value1, String value2) {
			addCriterion("del_flag not between", value1, value2, "delFlag");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table biz_safe_task_info
	 * @mbg.generated  Thu Jun 13 17:08:02 CST 2019
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table biz_safe_task_info
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 13 17:00:45 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}